# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/circuit_tr_signal.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_compteur_nbits_0_0/design_1_compteur_nbits_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_compteur_nbits_0_0 || ORIG_REF_NAME==design_1_compteur_nbits_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg_24b_0_0/design_1_reg_24b_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reg_24b_0_0 || ORIG_REF_NAME==design_1_reg_24b_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg_24b_0_1/design_1_reg_24b_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reg_24b_0_1 || ORIG_REF_NAME==design_1_reg_24b_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg_dec_24b_0_0/design_1_reg_dec_24b_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reg_dec_24b_0_0 || ORIG_REF_NAME==design_1_reg_dec_24b_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mef_decod_i2s_v1b_0_0/design_1_mef_decod_i2s_v1b_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mef_decod_i2s_v1b_0_0 || ORIG_REF_NAME==design_1_mef_decod_i2s_v1b_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_compteur_nbits_0_1/design_1_compteur_nbits_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_compteur_nbits_0_1 || ORIG_REF_NAME==design_1_compteur_nbits_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mef_cod_i2s_vsb_0_0/design_1_mef_cod_i2s_vsb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mef_cod_i2s_vsb_0_0 || ORIG_REF_NAME==design_1_mef_cod_i2s_vsb_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux2_0_0/design_1_mux2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mux2_0_0 || ORIG_REF_NAME==design_1_mux2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg_dec_24b_fd_0_0/design_1_reg_dec_24b_fd_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reg_dec_24b_fd_0_0 || ORIG_REF_NAME==design_1_reg_dec_24b_fd_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_1/design_1_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_1 || ORIG_REF_NAME==design_1_xlconstant_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_affhexPmodSSD_v3_0_0/design_1_affhexPmodSSD_v3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_affhexPmodSSD_v3_0_0 || ORIG_REF_NAME==design_1_affhexPmodSSD_v3_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_calcul_param_1_0_0/design_1_calcul_param_1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_calcul_param_1_0_0 || ORIG_REF_NAME==design_1_calcul_param_1_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_calcul_param_2_0_0/design_1_calcul_param_2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_calcul_param_2_0_0 || ORIG_REF_NAME==design_1_calcul_param_2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_calcul_param_3_0_0/design_1_calcul_param_3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_calcul_param_3_0_0 || ORIG_REF_NAME==design_1_calcul_param_3_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux4_0_0/design_1_mux4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mux4_0_0 || ORIG_REF_NAME==design_1_mux4_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux4_0_1/design_1_mux4_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mux4_0_1 || ORIG_REF_NAME==design_1_mux4_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sig_fct_3_0_0/design_1_sig_fct_3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_sig_fct_3_0_0 || ORIG_REF_NAME==design_1_sig_fct_3_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sig_fct_sat_dure_0_0/design_1_sig_fct_sat_dure_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_sig_fct_sat_dure_0_0 || ORIG_REF_NAME==design_1_sig_fct_sat_dure_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sig_fct_sat_dure_0_1/design_1_sig_fct_sat_dure_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_sig_fct_sat_dure_0_1 || ORIG_REF_NAME==design_1_sig_fct_sat_dure_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_module_commande_0_0/design_1_module_commande_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_module_commande_0_0 || ORIG_REF_NAME==design_1_module_commande_0_0} -quiet] -quiet

# XDC: c:/Users/gabma/Downloads/pb_logique_seq.xpr/pb_logique_seq/pb_logique_seq.gen/sources_1/bd/design_1/design_1_ooc.xdc
